
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: local

  redis:
    host: localhost
    port: 6379
    password: 'board'

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_SECRET}
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

            kakao:
              client_id: ${KAKAO_CLIENT_ID}
              redirect_uri: http://localhost:8080/login/oauth2/code/kakao
              client-authentication-method: POST
              response_type: code
              scope:
                - profile_nickname
                - account_email
              client-name: Kakao
              authorization-grant-type: authorization_code

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: http://kauth.kakao.com/oauth/authorize
            token-uri: http://kauth.kakao.com/oauth/token
            user-info-uri: http://kauth.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  key: ${JWT_SECRET_KEY}
  refresh-token-expiration-minutes: 420
  access-token-expiration-minutes: 360

mail:
  address:
    admin: ${ADMIN_EMAIL_ADDRESS}